config/routes.rb
BarterMe::Application.routes.draw do
  
  resources :locations

  root 'welcome#index'
   post 'pusher/auth'
  
  get '/loaderio-8968c2e71cf3502dbd55d8cc12dcb850' => redirect('/loaderio-8968c2e71cf3502dbd55d8cc12dcb850.txt')

  resources :line_items

  resources :carts, :path => "watchlist"
  
  resources :categories

  resources :offer_forms, only: [:new, :create]
  
  controller :admin do
    get 'admin' => :index
  end
  
  controller :welcome do
    get 'listings' => :all_listings
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  controller :profiles do
    get 'profile' => :profile
    get 'profile/:id' => :profile
  end

  resources :offers do
    get :accept, :on => :member
    get :reject, :on => :member
    post 'offers/new' => :new
    resources :comments, only: [:index, :new, :create]
  end

  resources :users
  
  resources :ratings
  
  resources :items do
    collection do
      get 'search'
      get 'my_items'
    end
  end
  
end

  

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :user, foreign_key: "user_id"
  
  def add_item(item_id)
    
    current_item = line_items.find_by(item_id: item_id) 
    if !current_item
      current_item = line_items.build(item_id: item_id)
    else
      return -1
    end
    
   return current_item
    
  end
  
  
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Your watchlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
 def destroy
    if  @cart.id == session[:cart_id]  
      remove_line_items
    end

    respond_to do |format|
      format.html { redirect_to @cart,
        notice: 'Your watchlist is currently empty' }
      format.json { head :no_content }
    end
  end

  # def destroy
  #   @cart.destroy
  #   respond_to do |format|
  #     format.html { redirect_to "/" }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def remove_line_items
      @cart.line_items.each do |li|
        if li.cart_id == @cart.id
          li.delete
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to "/", notice: 'Invalid cart'
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<style>
h3 {
  margin-top: 0px;
  margin-bottom: 0px;
}
</style>



<% if flash[:notice] %>
<div class = "alert alert-danger alert-dismissible"  role="alert" style="margin-top:10px">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="top:-13px"><span aria-hidden="true">&times;</span></button>
  <h3><%= flash[:notice] %></h3>
</div>
<% end %>

<h2>Your Watchlist</h2>
<div class="row">
	<div class="col-md-10" style="padding-top:10px">
	<ul>
		<table class="table table-striped">
			<% @cart.line_items.each do |item| %>
			<%if item_available?(item.item.id)%>
			<tr class="<%= cycle('list_line_odd', 'list_line_even') %>" align="left" width="20%" style="border-bottom: 5px solid #ccc; border-top: 5px solid #ccc">
				
				<td>
					<%= image_tag item.item.image_url, :size => "100x100"  %>
				</td>
				<td class="list_description" align="left" width="50%">
					<dl>
						<dt><%= link_to item.item.name, item_path(item.item) %></dt>
						<dd><%= truncate(strip_tags(item.item.description), length: 80) %></dd>
					</dl>
				</td>
				<td>
					<%= link_to 'Show', item_path(item.item),class: 'btn btn-primary btn-md btn-block'  %>
					<%= link_to 'Remove', item, method: :delete, data: { confirm: 'Are you sure?' },
					class: 'btn btn-primary btn-md btn-block' %>
				</td>
			</tr>
			<% end %> 
			<% end %> 
		</table>
	</ul>
	</div>
</div>

<!--<%= link_to 'Edit', edit_cart_path(@cart) %> -->
<div class="col-md-2" style="margin-left: 20px">
  <%= link_to 'Back', items_path,class: 'btn btn-primary btn-lg'  %>
</div>
<div class="col-md-6"></div>
<div class="col-md-2">
  <%= button_to 'Remove All', @cart, method: :delete,
      data: { confirm: 'Are you sure?' }, class: 'btn btn-danger pull-right btn-lg ', type: 'button' %>
</div>