config/routes.rb
BarterMe::Application.routes.draw do
  
  resources :locations

  root 'welcome#index'
   post 'pusher/auth'
  
  get '/loaderio-8968c2e71cf3502dbd55d8cc12dcb850' => redirect('/loaderio-8968c2e71cf3502dbd55d8cc12dcb850.txt')

  resources :line_items

  resources :carts, :path => "watchlist"
  
  resources :categories

  resources :offer_forms, only: [:new, :create]
  
  controller :admin do
    get 'admin' => :index
  end
  
  controller :welcome do
    get 'listings' => :all_listings
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  controller :profiles do
    get 'profile' => :profile
    get 'profile/:id' => :profile
  end

  resources :offers do
    get :accept, :on => :member
    get :reject, :on => :member
    post 'offers/new' => :new
    resources :comments, only: [:index, :new, :create]
  end

  resources :users
  
  resources :ratings
  
  resources :items do
    collection do
      get 'search'
      get 'my_items'
    end
  end
  
end

  

app/models/offer.rb
class Offer < ActiveRecord::Base

	has_many :items
	has_many :comments

	belongs_to :user1, class_name: "User", foreign_key: "user1_id"	 
	belongs_to :user2, class_name: "User", foreign_key: "user2_id" 

	validates_presence_of :user1_id
	validates_associated :user1

	validates_presence_of :user2_id
	validates_associated :user2

	private

	 def verify_item2
	 	check_availabity(self[:item2_id])
	 end

	 def verify_item1
	 	check_availabity(self[:item1_id])
	 end

	 def check_availabity(items_list)
	 	ids = items_list.split(",").map(&:to_i)
	 	ids.each do |id|
	 		unless Item.exists?(id)
	 			errors.add(items_list,"offer contains unavailable item(s)")
	 		end 
	 	end
	 end


	def self.proposed?(user)
    	offers2 = Offer.where(:user2_id => user.id)
  	end

  	def self.received?(user)
  		offers1 = Offer.where(:user1_id => user.id)
  	end

  	def  self.mine?(user)
  		return @offer.user2_id == user.id
  	end

  	def self.pending?
  		@offers = Offer.where(:pending => true)
  	end


end

app/models/offer_form.rb
 class OfferForm
 	include ActiveModel::Validations
 	include ActiveModel::Conversion
 	extend ActiveModel::Naming

 	attr_accessor :item1_ids, :item2_ids

 	validate :must_ask_for_one
 	validate :must_offer_one
 	validate :items_must_belong_to_one_user

 	def must_ask_for_one
 		unless self.item1_ids.has_value?("1")
 			errors.add(:item1_ids, "Must check at least one item to barter for")
 		end

 		self.items_must_belong_to_one_user

 	end

 	def must_offer_one
 		unless self.item2_ids.has_value?("1")
 			errors.add(:item2_ids, "Must check at least one item to offer")
 		end
 	end

 	def items_must_belong_to_one_user
 		items = Item.find(self.item1_ids.select{|k,v| v == "1"}.keys)

 		unless items.empty?
 			uid = items[0].user_id
 			items.each do |it|
 				if it.user_id != uid && errors[:item1_ids].empty?
 					errors.add(:item1_ids, "Items must belong to the same user")
 					break
 				end
 			end
 		end
 	end

 	def transform

 		item1_ids = self.item1_ids.select{|k,v| v == "1"}.keys
 		item2_ids = self.item2_ids.select{|k,v| v == "1"}.keys
 		item1 = Item.find(item1_ids)
 		item2 = Item.find(item2_ids)
 		user1_id = item1[0].user_id
 		user2_id = item2[0].user_id
 		item1_names = []
 		item2_names = []
 		item1.each { |i| item1_names << i.name }
 		item2.each { |i| item2_names << i.name }

 		transformed = {:item1_ids => self.item1_ids.select{|k,v| v == "1"}.keys,
 						:item2_ids => self.item2_ids.select{|k,v| v == "1"}.keys,
 						:user1_id => user1_id,
 						:user2_id => user2_id,
 						:item1_names => item1_names.join(", "),
 						:item2_names => item2_names.join(", ")
 						}
 		return transformed
 	end




 	def initialize(attributes = {})
 		attributes.each do |name, value|
 			send("#{name}=", value)
 		end
 	end

 	def persisted?
 		false
 	end

 end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    user = User.find_by(id: session[:user_id])
    proposed_offers = Offer.proposed? user
    received_offers = Offer.received? user
    offers = received_offers.concat(proposed_offers)
    if (params[:pending]=="all" || params[:pending].nil?)
      @offers = offers
    else
      @offers = offers.select {|o| o.pending == (params[:pending]=="true")}
    end
 end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @offer }
        Rating.create(:offer_id => @offer.id, :user_id=>@offer.user1_id, :score => 0)
        Rating.create(:offer_id => @offer.id, :user_id=>@offer.user2_id, :score => 0)
      else
        format.html { redirect_to offers_url, notice: 'Offer invalid.' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update

    params[:offer][:item1_id] = params[:offer][:item1_id].select{|k,v| v == "1"}.keys.join(",")
    params[:offer][:item2_id] = params[:offer][:item2_id].select{|k,v| v == "1"}.keys.join(",")

    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  def accept
    set_offer
    update_accepted(@offer.item1_id)
    update_accepted(@offer.item2_id)
    @offer.update_attributes(:accepted => true, :pending => false)
    Pusher['private-'+@offer.user2_id.to_s].trigger('offer_update', {:offer => @current_user.user_name})
    redirect_to offers_url
  end

  def reject
    set_offer
    @offer.update_attributes(:accepted => false, :pending => false)
    Pusher['private-'+@offer.user2_id.to_s].trigger('offer_update', {:offer => @current_user.user_name})
    redirect_to offers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:user1_id, :user2_id, :item1_id, :item2_id, :accepted, :pending, :rating)
    end

    def update_accepted(items_list)
      ids = items_list.split(",").map(&:to_i)
      ids.each do |id|
        this_item = Item.find(id)
        this_item.update_attributes(:quantity => this_item.quantity-1)
      end
    end
  
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_detail.html.erb
<% @offer = Offer.find(params[:id])%>


<div class="col">
  <div class="container-fluid" style="margin-bottom: 1px">
    <div class="row" style="padding-left:20px;">
      <p>
        <% proposer = User.find(@offer.user2_id)%>
        <% proposee = User.find(@offer.user1_id)%>
        <% if (session[:user_id] == proposer.id.to_i)%>
          <% proposer_str = "You are "%>
          <% proposee_str = proposee.user_name + "'s "%>
        <% else %>
          <% proposer_str = proposer.user_name + " is "%>
          <% proposee_str =  "your "%>
        <% end %>
        <h3><%= link_to proposer.user_name, "/profile/#{proposer.id}"%><%=" is offering items"%><b></h3>
        <table class="table table-striped">
          <% @offer.item2_id.split(",").each do |id|%>
          <% item = Item.find(id.to_i) %>
          <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td align="left" width="20%">
              <%= image_tag item.image_url, :size => "200x200" %>
            </td>
            <td class="list_description" align="left" width="80%">
              <dl>
                <h5><b><%= link_to item.name, "/items/#{item.id}" %><b></h5>
                <dd><%= truncate(strip_tags(item.description), length: 100) %></dd>
              </dl>
            </td>
          </tr>
          <% end %>
        </table>
      </p>
    </div>
    <div class="span4">
      <div class="row" style="padding-left:20px;">
        <h3><%= " for " + proposee_str + " items:" %></h3>
      </p>
      <table class="table table-striped">
        <% @offer.item1_id.split(",").each do |id|%>
        <% item = Item.find(id.to_i) %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td align="left" width="20%">
            <%= image_tag item.image_url, :size => "200x200" %>
          </td>
          <td class="list_description" align="left" width="80%">
            <dl>
              <h5><b><%= link_to item.name, "/items/#{item.id}" %><b></h5>
              <dd><%= truncate(strip_tags(item.description), length: 100) %></dd>
            </dl>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<p>
  <h4>Status:</h4>
  <% if @offer.pending %>
  <td><h4><span class="label label-default label-lg">Pending</span></h4></td>
  <% else%>
  <% if @offer.accepted %>
  <td><h4><span class="label label-success label-lg">Accepted</span></h4></td>
  <% else %>
  <td><h4><span class="label label-danger label-lg">Rejected</span></h4></td>
  <% end %>
  <% end %>
</p>
</div>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :item1_id %><br>
    <%= f.text_field :item1_id %>
  </div>
  <div class="field">
    <%= f.label :item2_id %><br>
    <%= f.text_field :item2_id %>
  </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>


<% proposer = User.find(@offer.user2_id)%>
<% proposee = User.find(@offer.user1_id)%>
<% if (session[:user_id] == proposer.id.to_i)%>
<% proposer_str = "You are "%>
<% proposee_str = proposee.user_name + "'s "%>
<% else %>
<% proposer_str = proposer.user_name + " is "%>
<% proposee_str =  "your "%>
<% end %>


<%= form_for(@offer, :url =>  {:action => 'update'}) do |f| %>

<div class="row" style="margin-bottom: 100px">
	<div class="container-fluid" style="margin-bottom: 1px">
		<div class="row">
			<p style="right:80px"></p>
			<ul>
				<h2><%= link_to proposer.user_name, "/profile/#{proposer.id}"%> is offering:</h2>
				<table class="table table-striped">
					<% items2 = Item.mine?(proposer) %>
					<% contained = @offer.item2_id.split(",") %>
					<%= f.fields_for :item2_id do |cb| %>
					<% items2.each do |item| %>
					<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
						<td class="form-group">
							<%= cb.check_box(item.id, {checked: contained.include?(item.id.to_s)}) %>
							<td>
								<%= image_tag item.image_url, :size => "100x100" %>
							</td>
							<td class="list_description">
								<dl>
									<dt><%= link_to item.name, item_path(item) %></dt>
									<dd><%= truncate(strip_tags(item.description), length: 80) %></dd>
								</dl>
							</td>
						</td>
						<% end %>
						<% end %>
					</tr>
				</table>
			</ul>
		</div>
		<div class="row">
			<p style="right:80px"></p>
			<ul>
				<h2>for <%= proposee_str %> items:</h2>
				<table class="table table-striped">
					<% items1 = Item.mine?(proposee) %>
					<% contained = @offer.item1_id.split(",") %>
					<%= f.fields_for :item1_id do |cb| %>
					<% items1.each do |item| %>
					<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
						<td class="form-group">
							<%= cb.check_box(item.id, {checked: contained.include?(item.id.to_s)}) %>
							<td>
								<%= image_tag item.image_url, :size => "100x100" %>
							</td>
							<td class="list_description">
								<dl>
									<dt><%= link_to item.name, item_path(item) %></dt>
									<dd><%= truncate(strip_tags(item.description), length: 80) %></dd>
								</dl>
							</td>
						</td>
						<% end %>
						<% end %>
					</tr>
				</table>
			</ul>
		</div>
	</div>
	
	<div class="actions">
		<%= f.submit "Submit edit", :class => 'myButton' %>
	</div>


	<%= link_to 'Back', offers_path %>
	
</div>

<% end %>

app/views/offers/index.html.erb
<style>
h3 {
  margin-top: 0px;
  margin-bottom: 0px;
}
</style>


<% if flash[:notice] %>
<div class = "alert alert-success alert-dismissible"  role="alert" style="margin-top:10px">
<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="top:-13px"><span aria-hidden="true">&times;</span></button>
<h3><%= flash[:notice] %></h3>
</div>
<% end %>


<h1>Offers Made To Me and By Me</h1>

Filter offer by status: 
<%= form_tag offers_path, method: 'get' do %>
<%= select_tag 'pending', options_for_select({"all" => "all", "Pending" => true, "Responded" => false},"all") %>
<%= submit_tag 'Filter', class: 'btn btn-primary btn-md' %>
<% end %>

<div class="row">
  <div class="col-md-10" style="padding-top:10px; border-bottom: 1px solid #ccc">
    <table class="table table-striped">
      <thead>
         <th>Proposee</th>
         <th>Proposer</th>
         <th>Items desired</th>
         <th>Items offered</th>
         <th>Status</th>
         <th>You rated this barter:</th>
     </thead>
     <tbody>
      <% @offers.each do |offer| %>
        <% item1_ids = offer.item1_id.split(",") %>
        <% item2_ids = offer.item2_id.split(",") %>
        <% user1 = User.find(offer.user1_id) %>
        <% user2 = User.find(offer.user2_id) %>
        <% item1 = Item.find(item1_ids) %>
        <% item2 = Item.find(item2_ids) %>
        <tr>

          <td><b><%= link_to user1.user_name, "/profile/#{user1.id}"%></td>
          <td><b><%= link_to user2.user_name, "/profile/#{user2.id}"%></td>
          <%count = 0%>
          <td><% item1.each do |i|%>
              <b><%= link_to i.name, "items/#{i.id}"%>
              <%if count < item1.length - 1%> 
              <%=", "%>
              <%end%> 
              <%end%></td>
          <%count = 0%>
          <td><% item2.each do |i|%>
            <b><%= link_to i.name, "items/#{i.id}"%>
            <%if count < item2.length - 1%> 
              <%=", "%>
              <%end%> 
              <%end%></td>

          <% if offer.pending %>
            <td><h4><span class="label label-default label-lg">Pending</span></h4></td>
          <% else%>
            <% if offer.accepted %>
              <td><h4><span class="label label-success label-lg">Accepted</span></h4></td>
            <% else %>
              <td><h4><span class="label label-danger label-lg">Rejected</span></h4></td>
            <% end %>
          <% end %>

          <% r = Rating.find_by(offer_id: offer.id, user_id: offer.user1_id + offer.user2_id - @current_user.id)%>
          <td>
            <% if offer.accepted? %>
            <%= image_tag  r.score.to_i.to_s + '_star.png', :size => "120x24"  %></td>
            <% else %>
            <%= "Rating available after" %></br>
            <%= "the barter is accepted."%>
            <% end %>
          <td>
            <%= link_to 'View offer', offer_path(offer), class: 'btn btn-primary btn-md btn-block'%>
            <% if offer.pending %>
              <% if offer.user1_id == @current_user.id%>
                <%= link_to 'Accept', accept_offer_path(offer),
                data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-md btn-block' %>
                <%= link_to 'Reject', reject_offer_path(offer),
                data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-md btn-block' %> 
              <% else %>
                <%= link_to 'Retract', offer, method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-md btn-block' %> 
              <% end %>
            <% end %>
            <%= link_to 'Comment', new_offer_comment_path(offer), class: 'btn btn-primary btn-md btn-block' %> 
          </td>


        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

app/views/offers/new.html.erb
<h1>Review your offer</h1>


<div class="col">
  <div class="container-fluid" style="margin-bottom: 1px">
    <div class="row" style="padding-left:20px;">
      <p>
        <% proposer = User.find(params[:user2_id])%>
        <% proposee = User.find(params[:user1_id])%>
        <h2>
          <% if proposer.id == @current_user.id %>
          <%= "You are offering items:"%>
          <% else %>
          <%= link_to proposer.user_name, "/profile/#{proposer.id}"%><%= " is offering items:"%>
          <% end %>
        </h2>
        <table class="table table-striped">
          <% params[:item2_ids].each do |id|%>
          <% item = Item.find(id) %>
          <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
            <td>
              <%= image_tag item.image_url, :size => "100x100" %>
            </td>
            <td class="list_description">
              <dl>
                <h4><%= link_to item.name, "/items/#{item.id}" %></h4>
                <dd><%= truncate(strip_tags(item.description), length: 100) %></dd>
              </dl>
            </td>
          </tr>
          <% end %>
        </table>
      </p>
    </div>
    <div class="span4">
      <div class="row" style="padding-left:20px;">
          <h2>
          <% if proposee.id == @current_user.id %>
          <%= "for your items:"%>
          <% else %>
          <%= " for "%><%= link_to proposee.user_name, "/profile/#{proposee.id}"%><%="'s items:" %>
          <% end %>
        </h2>
      </p>
      <table class="table table-striped">
        <% params[:item1_ids].each do |id|%>
        <% item = Item.find(id) %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td>
            <%= image_tag item.image_url, :size => "100x100" %>
          </td>
          <td class="list_description">
            <dl>
              <h4><%= link_to item.name, "/items/#{item.id}" %></h4>
              <dd><%= truncate(strip_tags(item.description), length: 100) %></dd>
            </dl>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<%= button_to "Confirm Offer", {action: "create", offer: {:user1_id=>params[:user1_id], :item1_id=>params[:item1_ids].join(","), :user2_id=>params[:user2_id], :item2_id=>params[:item2_ids].join(","), :accepted=>false, :pending=>true} }, :class => 'myButton' %>

<%= button_to 'back', new_offer_form_path, :method => :get, class: 'btn btn-primary btn-md' %>

app/views/offers/show.html.erb
<style>
h3 {
  margin-top: 0px;
  margin-bottom: 0px;
}
</style>


<% if flash[:notice] %>
<div class = "alert alert-success alert-dismissible"  role="alert" style="margin-top:10px">
<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="top:-13px"><span aria-hidden="true">&times;</span></button>
<h3><%= flash[:notice] %></h3>
</div>
<% end %>

<%= render :partial => 'detail', :locals => {:offer => @offer} %>

<% if @offer.accepted? %>

<% other_user = User.find(@offer.user1_id + @offer.user2_id - @current_user.id) %>
<p>
  <h4><%= other_user.user_name + " rated you:" %></h4>
  <% ry = Rating.find_by(offer_id: params[:id], user_id: @current_user.id)%>
  <%= image_tag ry.score.to_i.to_s + '_star.png', :size => "150x30"  %>
</p>

<p>
  <h4><%= "You rated " + other_user.user_name + ":"%></h4>
  <% ro = Rating.find_by(offer_id: params[:id], user_id: other_user.id)%> 
  <%= image_tag ro.score.to_i.to_s + '_star.png', :size => "150x30"  %>
</p>


<div class="row">
  <div class="col-md-10" style="padding-top:10px; border-bottom: 1px solid #ccc">
    <%= render :partial => 'ratings/form', :locals => {:offer => @offer}  %>
  </div>
</div>

<% end %>



<div class="row">
  <div class="col-md-10" style="padding-top:10px; border-bottom: 1px solid #ccc">
   <table class="table table-striped">
    <thead>
    </thead>
    <% @offer.comments.each do |c| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
     <td class="col-md-2">
       <%= c.from %>
       <%= "said:" %>
     </td>
     <td>
      <%= c.message %>
    </td>
    <td class="col-md-6">
      <td>
        <%= c.created_at.to_s.delete("UTC") %>
      </td>
    </td>
  </tr>
  <% end %>
</table>

<%= render :partial => 'comments/form', :params => @offer %>


</div>
</div>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>