config/routes.rb
BarterMe::Application.routes.draw do
  
  resources :locations

  root 'welcome#index'
   post 'pusher/auth'
  
  get '/loaderio-8968c2e71cf3502dbd55d8cc12dcb850' => redirect('/loaderio-8968c2e71cf3502dbd55d8cc12dcb850.txt')

  resources :line_items

  resources :carts, :path => "watchlist"
  
  resources :categories

  resources :offer_forms, only: [:new, :create]
  
  controller :admin do
    get 'admin' => :index
  end
  
  controller :welcome do
    get 'listings' => :all_listings
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  controller :profiles do
    get 'profile' => :profile
    get 'profile/:id' => :profile
  end

  resources :offers do
    get :accept, :on => :member
    get :reject, :on => :member
    post 'offers/new' => :new
    resources :comments, only: [:index, :new, :create]
  end

  resources :users
  
  resources :ratings
  
  resources :items do
    collection do
      get 'search'
      get 'my_items'
    end
  end
  
end

  

app/models/item.rb
class Item < ActiveRecord::Base

  has_many :line_items
 # before_destroy :ensure_not_referenced_by_any_line_item

  validates :name, :description, :quantity, presence: true
  validates :quantity, numericality: {greater_than: -1}
  validates_uniqueness_of :name, scope: :user_id
  belongs_to :user, foreign_key: "user_id",inverse_of: :items
  validates_presence_of :user

  belongs_to :category, foreign_key: "category_id"
  validates_presence_of :category

  mount_uploader :image_url, ImageUploader
  searchkick word_start: [:name]
  
  def self.listing
    listings = Hash.new
    Item.all.each do |item|
      if listings.has_key?(item.category.name)
        listings[item.category.name] += 1
      else
        listings[item.category.name] = 1
      end
    end
      sorted_listing = listings.sort_by {|k,v| -v} 
      return sorted_listing
  end
  
  def search_data
    {
      name: name,
      description: description,
      category: category.name
    }
  end
  
  def self.advsearch(params)
    if params 
      if params[:match_all] == "1" #implement the AND logic
        find(:all, :conditions => ['name LIKE ? AND description LIKE ?',"%#{params[:name]}%", "%#{params[:description]}%"])
      else
        params.each do |k, v|
          params[k] = "++" if params[k] == "" #by default, if a field is left blank, we can change from the ignore syntax "" to a filler
        end
        find(:all, :conditions => ['name LIKE ? OR description LIKE ?',"%#{params[:name]}%", "%#{params[:description]}%"])
      end
    else
      find(:all) 
    end
  end

  def self.mine?(user)
    @items  = Item.where(:user_id => user.id)
  end

 private

 # ensure that there are no line items referencing this product???????????
 def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show, :search]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_items

 def index
   @similarity_score = Array.new
   @categories = Item.listing
    if params[:query].present?
      @items = Item.search(params[:query], operator: :or,  page: params[:page], per_page: 10)
      if params[:order].present?
        @items = Item.order(params[:order])
      end
    else
      if params[:order].present? && params[:order]!="name"
        @items = Item.order(params[:order] + ' desc').page(params[:page])
      else
        @items = Item.order("name").page(params[:page])
      end
    end

   if logged_in?
    #Yahui is testing locations on score
      user2 = User.find_by(id: session[:user_id]) 
      @items.each do |item|
      @similarity_score.push(User.similarity_score(item.user.user_name, user2, params[:location]))
      end
   end


   count = @similarity_score.length-1
   (-count..-0).each do |i|
    if(@similarity_score[i] < 0) 
      @similarity_score.delete_at(i)
      @items.delete_at(i)
    end
  end

 end
 
 def search
   @items = Item.advsearch params
   respond_to do |format|
     format.js
     format.html
   end
 end

 def my_items
   user = User.find_by(id: session[:user_id])
   @items = Item.mine? user
 end

 # GET /items/1
 # GET /items/1.json
 def show  
 end

 def delete
 end
 
 # GET /items/new
 def new
   @item = Item.new
    
 end
 
 # GET /items/1/edit
 def edit
   if @item.user_id != @current_user.id
    redirect_to item_path(@item), notice: "Cannot edit items that aren't yours"
  end
 end
 
 # POST /items
 # POST /items.json
 def create
   
   @item = Item.new(item_params)
   user = User.find_by(id: session[:user_id])
   @item.user_id = user.id
   # category = Category.find_by name: params[:category]
   # @item.category_id = category.id

   
   respond_to do |format|
     if @item.save
       format.html { redirect_to @item, notice: 'Item was successfully created.' }
       format.json { render action: 'show', status: :created, location: @item }
     else
      puts(@item.errors.messages)
       format.html { render action: 'new' }
       format.json { render json: @item.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
 def update
    respond_to do |format|
     if @item.update(item_params)
       format.html { redirect_to @item, notice: 'Item was successfully updated.' }
       format.json { head :no_content }
     else
       format.html { render action: 'edit' }
       format.json { render json: @item.errors, status: :unprocessable_entity }
     end
   end
 end
 
 # DELETE /items/1
 # DELETE /items/1.json
 def destroy
  notice_str = "Item #{@item.name} deleted"
   @item.destroy
   respond_to do |format|
     format.html { redirect_to items_url, notice: notice_str}
     format.json { head :no_content }
   end
 end
 
 private
 # Use callbacks to share common setup or constraints between actions.
 def set_item
   @item = Item.find(params[:id])
 end
 
 # Never trust parameters from the scary internet, only allow the white list through.
 def item_params
   params.require(:item).permit(:name, :description, :image_url, :user_id, :location, :quantity, :category_id)
 end

 def invalid_items 
   logger.error "Attempt to access another user's items #{params[:id]}" 
   redirect_to "/", notice: 'Invalid cart'
 end
end

app/helpers/items_helper.rb
module ItemsHelper

  def user_looking_for(item)
    return User.looking_for?(item.user)
  end
  
  def matching_items(user, item)
   @possible_trades = Array.new
    user_wants = user_looking_for(item)
    my_items = Item.mine?(user)
    my_items.each do |my_item|
      if user_wants[my_item.category.name] == 0
        @possible_trades.push(my_item)
      end
    end
    return @possible_trades
  end




	def item_available?(id)
		
		q = Item.find(id).quantity

		if q > 0
			return true
		end

		return false
				
	end

	def belongs_to_current_user(id)
		user_id = Item.find(id).user_id
		return user_id == @current_user.id
	end

end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-5">
      <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name, @item.category_id)) %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, class: 'form-control' %>
  </div>
  <div class="actions" style="padding-top:10px">
    <%= f.submit "Submit", :class => "btn btn-large btn-primary" %>
  </div>

<div id="preview">
</div>

    </div>
  </div>
  <% end %>
  

app/views/items/_items.html.erb
 <div class="col-md-12" style="padding-top:2px; border-bottom: 2px solid #ccc">
  <td>
    <table class="table table-striped">
      <% @items.each_with_index do |item, index| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" style="border-bottom: 5px solid #ccc; border-top: 5px solid #ccc">
        <td style="width=200px" align="left" width="20%">
          <% if item.image_url.present? %>
          <%= image_tag item.image_url, :size => "150x150" %>
          <% else %>
          <%= image_tag "http://placehold.it/150&text="+item.name %>
          <% end %>
        </td>
        <td class="list_description" style="padding-left: 0px" align="left" width="50%">

          <dl>

           <dt><h3><%= link_to item.name, item_path(item) %></h3></dt>

           <dd><%= truncate(strip_tags(item.description), length: 100) %></dd><br>
	   
	   <% if logged_in? && item.user != @current_user %>
           <% matching = matching_items(@current_user, item) %>
           <% if !matching.empty? %>
	   <% wanted_item = matching.sample.name %>
           <a id="popoverData" href="#" data-content="<%=wanted_item%>" data-toggle="popover" rel="popover" data-placement="bottom" data-original-title="User May Want To Trade This Item for your:" data-trigger="hover"><b>This User may want your...</b></a>
           <% end %>
	   <% end %>
         </dl>
       </td>
       <td>
         <% if !@similarity_score.nil? && !@similarity_score.empty?%>
         <% if @similarity_score[index] < 30 %>
         <p class = "small" style="font-size:30px; color:red; padding-bottom:64px; padding-right:64px;">
          <% elsif @similarity_score[index] >= 30 && @similarity_score[index] < 70 %>
          <p class = "small" style="font-size:30px; color:yellow; padding-bottom:64px; padding-right:64px;">
           <% else %>
           <p class = "small" style="font-size:30px; color:green; padding-bottom:64px; padding-right:64px;">
             <% end %>
	     <% if @current_user.id == item.user_id %>
	     <p class = "small" style="font-size:30px; color:black; padding-bottom:64px; padding-right:64px;">
	       <%= "- - -" %>
	       <% else %>
               <%= @similarity_score[index].to_s + "%" %>
	       <% end %>
             <style> p.small {
              line-height: 148.55%;
              }</style>
              <% end %>
            </td>
          </td>
          <td class="list_actions">
            <% if logged_in? && admin? %>
            
            <%= link_to 'Show', item, class: 'btn btn-primary btn-md btn-block' %>
            <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-primary btn-md btn-block' %>
            <%= link_to 'Remove', item, method: :delete,
		data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-md btn-block' %> 
	    
            <% elsif logged_in? && item.user_id != @current_user.id %>
            <%if item_available?(item.id) && !belongs_to_current_user(item.id)%>
            <%= button_to 'Add to Watchlist', line_items_path(item_id: item), class: 'btn btn-primary btn-md btn-block' %><br/>
            <%end%>            
            <%= link_to 'Show', item, class: 'btn btn-primary btn-md btn-block' %>
            <% elsif logged_in? %>
            <%= link_to 'Show', item, class: 'btn btn-primary btn-md btn-block' %>
            <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-primary btn-md btn-block' %>
            <%= link_to 'Remove', item, method: :delete,
            data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-md btn-block' %> 
            <% else %>
            <%= link_to 'Show', item, class: 'btn btn-primary btn-md btn-block' %><br/>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </br>
  </div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<style>
h3 {
  margin-top: 0px;
  margin-bottom: 0px;
}
</style>



<% if flash[:notice] %>
<div class = "alert alert-danger alert-dismissible"  role="alert" style="margin-top:10px">
<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="top:-13px"><span aria-hidden="true">&times;</span></button>
<h3><%= flash[:notice] %></h3>
</div>
<% end %>



<script>
$(function () {
  $('[data-toggle="popover"]').popover();
});
</script>

<div class="row">
  <div class="col-md-3" >
    <h1>Available Items</h1>
  </div>
  <div class="col-md-2" style="padding-top:20px">
    <%= link_to 'Add New Item', new_item_path, class: 'btn btn-success btn-lg btn-block pull-left' %>
  </div>
</div>

<div class="row" style="padding-top:10px">
 <div class="col-md-3" style="padding-top:10px">
  <td class="form-group">
   <%= form_tag items_path, class: "form-inline", method: :get do %>
   <%= text_field_tag :query, params[:query], class: "form-control", :style => "width:170px"%>    
   <%= submit_tag "Search", class: "btn btn-primary" %></br>
   <% if params[:query].present? %>    
   <%= link_to "clear", items_path%>
   <% end %>
   <% end %>
   <%= link_to 'Advanced Search', search_items_path %>
 </td>
</div>
<div class="col-md-3" style="padding-top:10px">
 <td class="form-group">
   <%= form_tag items_path, class: "form-inline", method: :get do %>
   <% options = options_for_select([['name', "name"], ['recently added', "created_at"], ['recently updated', "updated_at"]]) %>
   <%= select_tag(:order, options, class: "form-control", :style => "width:170px") %>
   <%= submit_tag "Order By", class: "btn btn-primary" %>
   <% end %>
 </td>

</div>
<div class="col-md-2" style="padding-left:75px; padding-top: 10px">
  <%if logged_in? %>
  <button type="button" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="bottom" data-content="The Can I Get it? score is determined by the items you own, what this user is looking for, and both of your reliability indexes.  It is out of 100, and a higher score means you have a better chance to get the item." id="popover">Can I get it?</button>
</div>
<div class="col-md-3">
 <td class="form-group">

  <%if has_location?(current_user.id)%>
  <%= form_tag items_path, class: "form-inline", method: :get do %>
  <%= label(:location, :"How far you're willing to travel?")%>
  <% options = options_for_select([['All miles', 24901],['10 miles', 10], ['20 miles', 20], ['50 miles', 50], ['100 miles', 100]]) %>
  <%= select_tag(:location, options, class: "form-control") %>
  <%= submit_tag "Apply", class: "btn btn-primary " %>
  <%end%>
  <%end%>
  <%end%>
</td>

</div>

</div>

<div class="row">
  <div class="col-md-10" style="padding-left:10px; padding-top: 10px">
    <%= render 'items' %>
  </div>

  <div class="col-md-2" style="padding-left:5px; padding-right:10px; padding-bottom: 10px; border-bottom: 1px solid #ccc; border-top: 1px solid #ccc; border-left: 1px solid #ccc; border-right: 1px solid #ccc">
   <div class="container-fluid">
     <h2>Our Listings</h2>
     <div style="font-size:15px">
       <% @categories.each do |k, v| %>
       <%= link_to k, items_path(:query => k) %>
       <%= "(" + "#{v}" + ")" %><br>
       <% end %> 
     </div>
   </div>
 </div>
</div>
<div style="font-size:20px">
  <div class="row">
    <div class="col-md-3">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/my_items.html.erb
<div class="row" style="padding-bottom:25px">
<div class="col-md-4" >
<h1>My Available Items</h1>
</div>
<div class="col-md-2" style="padding-top:25px">
<%= link_to 'New Item', new_item_path, class: 'btn btn-success btn-lg btn-block pull-left' %>
</div>
</div>
<div class="row">
<%= render 'items' %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<div class="row">
    <div class="col-md-3" style="padding-bottom:10px; border-bottom: 1px solid #ccc">
	 
<h1>SEARCH</h1>
<%= form_tag "search", method: "get", remote: true, :class => "form-inline", :role => "form"  do %>

<div class="form-group" style="margin-bottom: 20px">
  <label>Name</label>
  <br><%= text_field_tag :name, "", class: "form-control" %></br>
</div>
<div class="form-group" style="margin-bottom: 20px">
  <label>Description</label>
  <br> <%= text_area_tag :description, "", size: "24x2", class: "form-control" %></br>
</div>
<div class="form-group" style="margin-bottom: 20px">
  <label>Match All?</label>
  <%= check_box_tag(:match_all) %>
</div>

  <br><%= submit_tag("Search", class: "btn btn-default") %>
<% end %>

    </div>
    
  <div class="col-md-8" style="padding-left:20px; border-left: 1px solid #ccc;">
      <h1>Matching Items</h1>
      <div id="items">
      </div>

app/views/items/search.js.erb
$('#items').html("<%= escape_javascript (render(partial: 'items')) %>");

app/views/items/show.html.erb
<style>
h3 {
  margin-top: 0px;
  margin-bottom: 0px;
}
</style>


<% if flash[:notice] %>
<div class = "alert alert-success alert-dismissible"  role="alert" style="margin-top:10px">
<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="top:-13px"><span aria-hidden="true">&times;</span></button>
<h3><%= flash[:notice] %></h3>
</div>
<% end %>

<div class="row">
  <div class="col-md-5" style="padding-top:10px">
    <% if @item.image_url.present? %>
            <%= image_tag @item.image_url, :size => "400x400" %>
            <% else %>
            <%= image_tag "http://placehold.it/400&text="+@item.name %>
            <% end %>
    <div class="row" style="padding-left: 15px; padding-top:10px">
      <div class="col-md-5">
	<% if logged_in? && @item.user_id != @current_user.id %>
	<%= button_to 'Add to Watchlist', line_items_path(item_id: @item), class: 'btn btn-primary btn-md btn-block' %>
	<% end %>
	
	<% if logged_in? && @item.user_id == @current_user.id %>
	<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary btn-md btn-block'  %>
	<% end %>
      </div>
	<div class="col-md-5">
	     <%= link_to 'Back', items_path, class: 'btn btn-primary btn-md btn-block' %>
	</div>
    </div>
  </div>
<div class="col-md-6">
   <div class="jumbotron" style="margin-top: 10px; padding-top:10px">
     <div class="row" style="padding-bottom:5px">
       <div style="font-size:35px"><b>Owner:</b></div>
       <div style="font-size:20px; padding-top:5px"><a href=<%= "/profile/#{@item.user.id}" %>> <%= "#{@item.user.user_name}" %></a></div>
     </div>
      <div class="row">
      <div style="font-size:35px"><b>Description:</b></div>
      <div style="font-size:20px"><%= @item.description %></div>
    </div>
    <div class="row">
	<div style="font-size:35px"><b>Category:</b></div>
	<div style="font-size:20px"><%= Category.find(@item.category_id).name%></div>
    </div>
    <div class="row">
	<div style="font-size:35px"><b>Location:</b></div>
	<div style="font-size:20px"><%= @item.location %></div>
    </div>
    <div class="row">
      <div style="font-size:35px"><b>Quantity:</b></div>
      <div style="font-size:20px"><%= @item.quantity %></div>
    </div>
  </div>
</div>