config/routes.rb
BarterMe::Application.routes.draw do
  
  resources :locations

  root 'welcome#index'
   post 'pusher/auth'
  
  get '/loaderio-8968c2e71cf3502dbd55d8cc12dcb850' => redirect('/loaderio-8968c2e71cf3502dbd55d8cc12dcb850.txt')

  resources :line_items

  resources :carts, :path => "watchlist"
  
  resources :categories

  resources :offer_forms, only: [:new, :create]
  
  controller :admin do
    get 'admin' => :index
  end
  
  controller :welcome do
    get 'listings' => :all_listings
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
    delete 'logout' => :destroy
  end

  controller :profiles do
    get 'profile' => :profile
    get 'profile/:id' => :profile
  end

  resources :offers do
    get :accept, :on => :member
    get :reject, :on => :member
    post 'offers/new' => :new
    resources :comments, only: [:index, :new, :create]
  end

  resources :users
  
  resources :ratings
  
  resources :items do
    collection do
      get 'search'
      get 'my_items'
    end
  end
  
end

  

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # include CurrentCart
  # before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    item = Item.find(params[:item_id])
    @line_item = @cart.add_item(item.id)
    if @line_item == -1
      respond_to do |format|
        format.html {
          redirect_to items_url,
          notice: 'Item already in your watchlist'}
      end
    else
      respond_to do |format|
        if @line_item.save
          if item.user_id == session[:user_id]
            redirect_path = 'offer/new'
          else
            redirect_path = @line_item.cart
          end
          format.html { 
            redirect_to redirect_path,
            notice: 'Item added to your watchlist.' }
          format.json { render action: 'show', status: :created, location: @line_item }
        else
          format.html { render action: 'new' }
          format.json { render json: @line_item.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @line_item.cart }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:item_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :cart %><br>
    <%= f.text_field :cart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.item %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @line_item.item %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>